// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-g0us7MCI2dn_Y0QFPRaVNWapKbRg6mA',
    appId: '1:361702159474:web:dc188626e20899328b7eeb',
    messagingSenderId: '361702159474',
    projectId: 'brainmaximizer-c1889',
    authDomain: 'brainmaximizer-c1889.firebaseapp.com',
    storageBucket: 'brainmaximizer-c1889.firebasestorage.app',
    measurementId: 'G-EGVQZWQQDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBABgry-Is_6VGJX0XU_g_KnwUJ2Wx-l1Y',
    appId: '1:361702159474:android:7ac2fd15a8e3ca2b8b7eeb',
    messagingSenderId: '361702159474',
    projectId: 'brainmaximizer-c1889',
    storageBucket: 'brainmaximizer-c1889.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUrbJ_wWT_ORM1RbUtKTcnxsuqd1S7pXU',
    appId: '1:361702159474:ios:1726f0acb0c398bc8b7eeb',
    messagingSenderId: '361702159474',
    projectId: 'brainmaximizer-c1889',
    storageBucket: 'brainmaximizer-c1889.firebasestorage.app',
    iosBundleId: 'com.alaxhenry.brainmaximizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUrbJ_wWT_ORM1RbUtKTcnxsuqd1S7pXU',
    appId: '1:361702159474:ios:1726f0acb0c398bc8b7eeb',
    messagingSenderId: '361702159474',
    projectId: 'brainmaximizer-c1889',
    storageBucket: 'brainmaximizer-c1889.firebasestorage.app',
    iosBundleId: 'com.alaxhenry.brainmaximizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-g0us7MCI2dn_Y0QFPRaVNWapKbRg6mA',
    appId: '1:361702159474:web:ff985e97493b99f08b7eeb',
    messagingSenderId: '361702159474',
    projectId: 'brainmaximizer-c1889',
    authDomain: 'brainmaximizer-c1889.firebaseapp.com',
    storageBucket: 'brainmaximizer-c1889.firebasestorage.app',
    measurementId: 'G-BCNCWKVC93',
  );

}